<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyCyberQuiz.DAL\MyCyberQuiz.DAL.csproj" />
    <ProjectReference Include="..\MyCyberQuiz.Shared\MyCyberQuiz.Shared.csproj" />
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
